### ISSUE TITLE
Remove -l in nc revshell

### ISSUE THREAD

**Issue by clem9669** [0dayCTF/reverse-shell-generator#108]
Hi 👋 

As stated in man page, ***"-l' Used to specify that nc should listen for an incoming connection rather than initiate a connection to a remote host. It is an error to use this option in conjunction with the -p, -s, or -z options. Additionally, any timeouts specified with the -w option are ignored."***

I suggest to remove -p in the command for listener

Cheers

**Comment by clem9669** [comment]
https://linux.die.net/man/1/nc

**Comment by 0dayCTF** [comment]
Without the "-p" nc will generate a random port and not the one that you provide. Thank you :)
