### ISSUE TITLE
Self XSS (no impact)

### ISSUE THREAD

**Issue by 0dayCTF** [0dayCTF/reverse-shell-generator#131]
No character limit in the IP Address field created the possibility of a self XSS, I will fix this at a future time. If anyone can show impact, I'll fix it immediately :) 

P.S: Make sure to blame @AyhamAl-Ali 😂

**Comment by 0dayCTF** [comment]
![self_xss](https://user-images.githubusercontent.com/44453666/229313139-bacef240-4a35-4d0d-8c09-3fcbf879fc89.jpg)

**Comment by AyhamAl-Ali** [comment]
ops 😂

**Comment by 0dayCTF** [comment]
Thank you! I appreciate the help 🚀
