### ISSUE TITLE
[Domain donation] Would you like revshell.download?

### ISSUE THREAD

**Issue by whoisroot** [0dayCTF/reverse-shell-generator#144]
Hi

Some years ago I purchased the domain `revshell.download` with the intent of doing something similar to this project (which I was unaware existed). The domain is actually newer than this project, hehe 😅.

My registration expires in ~1 year, but if you accept this offer, I can renew it for another 3 years (maybe 5) and then transfer it to you.

Full disclosure: I purchased it in a nice deal at [porkbun.com](https://porkbun.com/tld/download) for ~ 4.25/year, if you want to buy it directly when it expires in August.

**Comment by 0dayCTF** [comment]
Thank you, I appreciate the offer! As of right now I am okay with how it is :)
