### ISSUE TITLE
This function has crashed

### ISSUE THREAD

**Issue by Reelix** [0dayCTF/reverse-shell-generator#168]
1.) Go to https://www.revshells.com/PowerShell%20%233%20(Base64)?ip=10.10.10.10&port=9002&shell=cmd&encoding=cmd

2.) See "This function has crashed"

**Comment by 0dayCTF** [comment]
Yes, having the same issue. It's from a commit that converted the base64 for UTF16-LE, I will get it resolved. Thank you!
