### ISSUE TITLE
Typo : One comma needs to be removed

### ISSUE THREAD

**Issue by mosecund** [0dayCTF/reverse-shell-generator#177]
Line 177 in the meta of PHP exec in data.js file,

"meta": ["linux", , "mac"]
should be changed to 
"meta": ["linux", "mac"]

<img width="566" alt="Capture d’écran 2024-10-31 à 13 28 19" src="https://github.com/user-attachments/assets/cc588853-34a7-40c3-a77c-8154ff234251">

**Comment by 0dayCTF** [comment]
Fixed, thank you!
