### ISSUE TITLE
PowerShell Base64 encoded command is not in the correct format

### ISSUE THREAD

**Issue by codebeta** [0dayCTF/reverse-shell-generator#51]
The `PowerShell #3 (Base64)` generates an invalid Base64 string and doesn't work when running it in Windows. This is the error seen when attempting to run the command in Windows 10.

```text
At line:1 char:1
+ 挤楬湥⁴‽敎⵷扏敪瑣匠獹整⹭敎⹴潓正瑥⹳䍔䍐楬湥⡴ㄢ㈷㌮⸱㈱⸰∸㐬〰⤰␻瑳敲浡㴠␠汣敩瑮䜮瑥瑓敲浡⤨嬻祢整嵛⑝祢整⁳‽⸰㘮㔵㔳╼笥細眻楨敬 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent
```

The string should be converted to UTF-16LE prior to encoding to Base64. In Linux, this can be done with the command `echo -n "whoami" | iconv -f UTF-8 -t UTF-16LE` .

**Comment by 0dayCTF** [comment]
I appreciate it, I'll fix it shortly. I am aware of the encoding for Windows, thank you for the example :)

**Comment by 0dayCTF** [comment]
Fixed!
