### ISSUE TITLE
advanced cannot work

### ISSUE THREAD

**Issue by zhjygit** [0dayCTF/reverse-shell-generator#74]
With on line mode,the advnced options is blank.
It is the same with another PC.
However,it works on my phone.
I have closed AV system and firewall.

**Comment by 0dayCTF** [comment]
It’s just a display bug, on mobile they show up regardless if you’ve enabled it. I’ll get around to fixing that, thank you.

**Comment by zhjygit** [comment]
OK，waiting for you.

**Comment by 0dayCTF** [comment]
Please post a screenshot from your Desktop.
