### ISSUE TITLE
Feature request: "Listener" card could update it's content depending on the type of shell

### ISSUE THREAD

**Issue by 0xless** [0dayCTF/reverse-shell-generator#75]
It would be great if the "Listener" card could list commands to connect to a shell depending on the type of shell being used.
I imagined that it could change it's content whenever a user selects a type of shell, but dedicated tabs/menus to navigate the connection options could work too.

**Comment by 0dayCTF** [comment]
I will look into a solution for this, feel free to contribute if you have any ideas!

Thank you
