### ISSUE TITLE
Incorrect URLEncode and Double URLEncode?

### ISSUE THREAD

**Issue by gblomqvist** [0dayCTF/reverse-shell-generator#82]
I'm guessing "URLEncode" is meant to perform URL encoding, but currently it doesn't encode any URL-reserved characters at all such as e.g. "&" or "/".

I'm further guessing "Double URLEncode" is meant to perform URL encoding twice, but currently it performs URL encoding once (but unlike "URLEncode" it performs complete URL encoding).

Another relevant issue is that HTML escaping is performed before the URL encoding, causing HTML entities to be URL encoded. E.g., "&" will be HTML escaped to "\&amp;" which in turn will be URL encoded to "%26amp%3B", but the expected encoding is "%26".

I suggest these issues are fixed by...
- letting "URLEncode" perform encoding using "encodeURIComponent" ([or perhaps the "fixedEncodeURIComponent" described at MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)? Maybe unnecessary),
- letting "Double URLEncode" do the same URL encoding as "URLEncode" but twice, and
- delay HTML-escaping until after URL encoding. If the URL encoding is fixed, then HTML-escaping should be unnecessary. However, it might be good practice to keep the HTML-escaping, but if so then not like it's done in `script.js` (substring substitution) but instead like it's done in `raw-link.js` (utilize `HTMLElement.innerText` or `Node.textContent`), i.e. leave escaping to the browser.

**Comment by 0dayCTF** [comment]
I appreciate the detailed description! If you'd like to take a shot at fixing this issue, that would be great.

**Comment by gblomqvist** [comment]
I took a shot and opened a PR. :)

**Comment by 0dayCTF** [comment]
Looks great, I appreciate the help. It appears to work perfectly now. Do you happen to have a Discord?

**Comment by gblomqvist** [comment]
Great, thanks. I do, I'm "gblomqvist", tag 7882.
